const BRAND = "#1f95ff";
const BRAND_DARK = "#1a7fd4";
const BRAND_BLUE = "#1677FF";
const GOLD = "#D4A853";

export default {
  brand: BRAND,
  brandDark: BRAND_DARK,
  blue: BRAND_BLUE,
  gold: GOLD,
  light: {
    text: "#1A1208",
    textSecondary: "#5A5040",
    textMuted: "#8C7F6A",
    background: "#F5F0E8",
    backgroundSecondary: "#EDE8DC",
    backgroundTertiary: "#E8E2D6",
    surface: "#F5F0E8",
    border: "#DDD7C9",
    tint: BRAND,
    tabIconDefault: "#8C7F6A",
    tabIconSelected: BRAND,
    bubble: "#1f95ff",
    bubbleText: "#FFFFFF",
    bubbleIncoming: "#EDE8DC",
    bubbleIncomingText: "#1A1208",
    inputBg: "#EDE8DC",
    header: "#F5F0E8",
    separator: "#DDD7C9",
    badgeBg: "#FF3B30",
    badgeText: "#FFFFFF",
    avatar: "#DDD7C9",
    online: "#1f95ff",
    unread: BRAND,
    icon: "#3A3A3C",
    iconMuted: "#8C7F6A",
  },
  dark: {
    text: "#F1F1F1",
    textSecondary: "#AAAAAA",
    textMuted: "#717171",
    background: "#0F0F0F",
    backgroundSecondary: "#272727",
    backgroundTertiary: "#1F1F1F",
    surface: "#0F0F0F",
    border: "#303030",
    tint: BRAND,
    tabIconDefault: "#717171",
    tabIconSelected: BRAND,
    bubble: "#1f95ff",
    bubbleText: "#FFFFFF",
    bubbleIncoming: "#272727",
    bubbleIncomingText: "#F1F1F1",
    inputBg: "#272727",
    header: "#0F0F0F",
    separator: "#303030",
    badgeBg: "#FF3B30",
    badgeText: "#FFFFFF",
    avatar: "#272727",
    online: "#1f95ff",
    unread: BRAND,
    icon: "#EBEBF5",
    iconMuted: "#636366",
  },
};
