import React from "react";
import {
  Linking,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from "react-native";
import { router } from "expo-router";
import { Ionicons } from "@expo/vector-icons";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useTheme } from "@/hooks/useTheme";

const EFFECTIVE_DATE = "May 16, 2026";
const LAST_UPDATED   = "May 16, 2026";
const TEAL = "#00BCD4";

type Section = { title: string; body: string };

const sections: Section[] = [
  // ─── 1. Introduction ───────────────────────────────────────
  {
    title: "Introduction",
    body: `AfuChat Limited ("AfuChat", "we", "us", "our") is committed to protecting your privacy and personal data. This Privacy Policy explains how we collect, use, disclose, store, and protect your information when you use the AfuChat platform — including our mobile apps (Android, iOS), web application, and associated services.\n\nThis Policy applies to all AfuChat products and services, regardless of the platform through which you access them. By using AfuChat, you consent to the practices described in this Policy. If you do not agree, you must stop using the Platform.`,
  },

  // ─── 2. Data We Collect ─────────────────────────────────────
  {
    title: "1. Information We Collect",
    body: `We collect information in three main ways:\n\n━ INFORMATION YOU PROVIDE\n\n• Account registration: email address, display name, username (handle), password (stored as a cryptographic hash — we never store your plaintext password), date of birth, gender, and country\n• Profile information: avatar, banner image, bio, phone number, website URL, and interests\n• Payment information: billing details for premium subscriptions and ACoin top-ups (processed by Pesapal — AfuChat never stores your card numbers or mobile money PIN)\n• Identity verification: government ID documents (submitted voluntarily for business/creator verification only)\n• Support communications: messages you send to our support team\n\n━ INFORMATION GENERATED BY YOUR USE\n\n• Content you create: posts, stories, comments, media uploads, broadcasts, and short videos\n• Communications: messages you exchange through the Platform (note: private 1-on-1 messages are end-to-end encrypted and their content is technically inaccessible to AfuChat)\n• Wallet & transaction data: ACoin balances, transaction history, transfer records, gift send/receive history\n• AI conversation history: your conversations with AfuAI (excluding private chat messages)\n• Usage data: features used, content viewed, interactions, search queries, and preferences\n• Device information: device type, model, operating system version, app version, timezone, language, and push notification tokens\n• Network information: IP address (used for location estimation and security), connection type\n\n━ INFORMATION FROM THIRD PARTIES\n\n• Third-party sign-in: when you sign in with Google, GitHub, X (formerly Twitter), GitLab, or Apple, we receive your name, email address, profile photo, and a provider-specific user ID. We never receive your password for those services.\n• App store platforms: basic installation and purchase data from Google Play and Apple App Store in accordance with their developer policies`,
  },

  // ─── 3. Third-Party Sign-In ─────────────────────────────────
  {
    title: "2. Third-Party Sign-In Providers",
    body: `AfuChat supports the following identity providers for account creation and sign-in:\n\n• Google\n• GitHub\n• X (formerly Twitter)\n• GitLab\n• Apple (on iOS / macOS)\n\nWhen you choose one of these options, you are redirected to the provider's secure login page. The provider returns a limited set of profile information — usually your name, email, avatar URL, and a stable user identifier — which we use to create or link your AfuChat account.\n\nWe do not see, receive, or store your password for any third-party provider.\n\nYou can revoke AfuChat's access at any time from your provider's account settings (e.g., Google Account → Security → Third-party apps). This prevents future sign-ins via that provider but does not delete your AfuChat account. To delete your account, use Settings → Account → Delete Account.\n\nAfuChat's use of information received from Google APIs adheres to the Google API Services User Data Policy, including the Limited Use requirements.`,
  },

  // ─── 4. How We Use Your Data ────────────────────────────────
  {
    title: "3. How We Use Your Information",
    body: `We use the information we collect for the following purposes:\n\n━ PROVIDING THE SERVICE\n• Create and manage your account\n• Enable messaging, social features, and community participation\n• Process payments and manage your wallet\n• Deliver content, notifications, and personalised recommendations\n• Provide customer support\n\n━ SAFETY & SECURITY\n• Detect, investigate, and prevent fraud, abuse, spam, and security incidents\n• Verify identity for business accounts and creator verification\n• Enforce our Terms of Service and Community Guidelines\n• Protect the rights and safety of users and the public\n\n━ IMPROVEMENT & ANALYTICS\n• Analyse usage patterns to improve the Platform\n• Debug errors and improve performance\n• Develop and test new features\n• Conduct aggregate, anonymised research\n\n━ COMMUNICATIONS\n• Send you product updates, security alerts, and account notifications\n• Send newsletters and marketing communications (only if you opt in)\n• Respond to your support requests\n\n━ LEGAL COMPLIANCE\n• Comply with applicable laws, regulations, and legal processes\n• Respond to lawful requests from government authorities`,
  },

  // ─── 5. Information Sharing ─────────────────────────────────
  {
    title: "4. Information Sharing & Disclosure",
    body: `We do not sell your personal information. We share your data only in these circumstances:\n\n━ WITH OTHER USERS\nYour public profile (display name, handle, avatar, bio, public posts, follower count) is visible to other AfuChat users and, if your account is public, to the broader internet including search engines.\n\n━ WITH SERVICE PROVIDERS\nWe engage trusted third-party companies to process data on our behalf:\n\n• Supabase (USA) — database, authentication, real-time infrastructure, and edge functions\n• Cloudflare R2 (global CDN) — media storage for avatars, posts, stories, and videos\n• Pesapal (Kenya/Uganda) — payment processing for subscriptions and top-ups\n• Resend (USA) — transactional email delivery (account notifications, newsletters)\n• Expo / EAS (USA) — app build, delivery, and OTA updates\n• Groq, OpenAI, and other AI providers — AI response generation (your prompts may be processed; providers are bound by data processing agreements)\n\nAll service providers are contractually obligated to protect your data and use it only as directed by AfuChat.\n\n━ FOR LEGAL REASONS\nWe may disclose your information if required by law, court order, or government authority, or if we believe disclosure is necessary to protect the rights, property, or safety of AfuChat, users, or the public.\n\n━ BUSINESS TRANSFERS\nIn the event of a merger, acquisition, or sale of all or part of AfuChat's assets, your information may be transferred. We will notify you of any such change and the choices available to you.\n\n━ WITH YOUR CONSENT\nWe may share your information for other purposes with your explicit consent.`,
  },

  // ─── 6. E2E Encryption ─────────────────────────────────────
  {
    title: "5. End-to-End Encrypted Messaging",
    body: `All private 1-on-1 messages on AfuChat are protected with end-to-end encryption (E2EE). This means:\n\n• Only you and the person you are messaging can read the content of your private messages\n• AfuChat's servers store messages in encrypted form that we cannot decrypt — even with a court order, we cannot produce the plaintext content of your private messages\n• No AfuChat employee, system, automated process, AI, or support agent can read your private chat messages\n• AfuAI is technically and programmatically prevented from accessing private chat content\n\nEnd-to-end encryption is enabled automatically for all direct (1-on-1) conversations.\n\n━ WHAT IS NOT END-TO-END ENCRYPTED\n• Group channels and community posts are not E2EE and are subject to content moderation\n• Public posts, stories, and broadcasts are visible to all\n• Your AI conversations with AfuAI are stored on our servers (but are not readable by other users)\n• Metadata (who you talked to, when, how often) may be stored for platform operation`,
  },

  // ─── 7. AfuAI & Data ───────────────────────────────────────
  {
    title: "6. AfuAI (AI Assistant) & Your Data",
    body: `AfuAI is our built-in AI assistant. When you use AfuAI, it may access the following to provide relevant responses:\n\n• Your public profile (name, handle, bio, grade/level)\n• Your wallet balances and recent transaction summaries\n• Your public posts, bookmarks, and social activity\n• Public platform data (trending posts, events, marketplace listings, channels)\n• Your follower and following connections\n\nAI PROCESSING: AfuAI uses third-party AI language model providers (including Groq and OpenAI) to generate responses. Your prompts and relevant platform context may be transmitted to these providers for processing. Providers are contractually bound not to use your data for training their models.\n\nCONVERSATION HISTORY: Your AfuAI conversations are stored to provide continuity. You can delete your AI conversation history at any time from the AfuAI screen → Settings → Clear History.\n\nAfuAI will NEVER:\n• Read, access, retrieve, or summarise any private (end-to-end encrypted) chat messages\n• Bypass end-to-end encryption on your conversations\n• Initiate transactions, send messages, or take any action without your explicit confirmation through an in-app approval prompt`,
  },

  // ─── 8. Your Rights ────────────────────────────────────────
  {
    title: "7. Your Rights & Choices",
    body: `You have the following rights regarding your personal data:\n\n• ACCESS: View your profile, posts, and account information at any time in the app\n• CORRECTION: Edit your profile, preferences, and account details in Settings\n• DELETION: Request permanent account deletion via Settings → Account → Delete Account. We will process deletion within 30 days. Some data may be retained in encrypted backups for up to 90 days before permanent purge.\n• DATA PORTABILITY: Request a copy of your data by contacting support@afuchat.com\n• WITHDRAWAL OF CONSENT: You can revoke permissions (location, camera, notifications) in your device settings at any time\n• OPT-OUT OF MARKETING: Unsubscribe from marketing emails using the unsubscribe link in any email, or update your preferences in Settings → Notifications\n• RESTRICTION: You can make your account private (Settings → Privacy → Account Visibility) to limit who sees your content\n• BLOCKING: Block users to prevent them from contacting you or seeing your content\n\n━ GDPR RIGHTS (EU/EEA/UK Users)\nIf you are located in the EU, EEA, or UK, you have additional rights under the General Data Protection Regulation (GDPR) or UK GDPR:\n• Right to be forgotten\n• Right to data portability\n• Right to object to processing\n• Right to lodge a complaint with your supervisory authority\n\nTo exercise any of these rights, contact privacy@afuchat.com. We will respond within 30 days.\n\n━ CCPA RIGHTS (California Residents)\nCalifornia residents have the right to know what personal information we collect, the right to delete personal information, and the right not to be discriminated against for exercising these rights. We do not sell personal information. Contact privacy@afuchat.com to submit a CCPA request.`,
  },

  // ─── 9. Cookies & Tracking ─────────────────────────────────
  {
    title: "8. Cookies, Local Storage & Tracking",
    body: `On the web version of AfuChat, we use browser local storage and session-based tokens to maintain your login state and preferences. We do not use third-party advertising cookies, cross-site tracking pixels, or fingerprinting technologies.\n\nAnalytics data is collected in aggregate, anonymised form to help us understand how the Platform is used and to improve it. We do not share individual-level analytics with third parties.\n\nOn our mobile apps, we use:\n• Secure on-device storage for authentication tokens\n• Push notification tokens to deliver notifications (stored on our servers)\n• App usage analytics in anonymised aggregate form`,
  },

  // ─── 10. Public Profiles & SEO ─────────────────────────────
  {
    title: "9. Public Profiles & Search Engine Indexing",
    body: `Public profile pages (e.g. afuchat.com/@yourhandle) and public posts (e.g. afuchat.com/p/<post-id>) are accessible to anyone on the internet, including search engines such as Google, Bing, and DuckDuckGo. We provide a public sitemap and structured data (Open Graph, Twitter Cards, JSON-LD) so these pages can be discovered and indexed.\n\nInformation visible on public pages — your display name, handle, bio, avatar, banner, follower count, and public posts — may appear in search results and link previews.\n\nDirect messages, drafts, wallet transactions, and content from private accounts are not included in our sitemap and are excluded from public indexing.\n\nTo prevent indexing of your account:\n• Switch to a private account in Settings → Privacy → Account Visibility\n• Delete specific posts or your entire account\n• Use Google's "Remove Outdated Content" tool for cached pages after deletion\n\nOur robots.txt disallows crawling of authenticated areas including messages, wallet, settings, login, search, and AI chat.`,
  },

  // ─── 11. Data Security ─────────────────────────────────────
  {
    title: "10. Data Security",
    body: `We implement industry-standard security measures to protect your data:\n\n• All data is encrypted in transit using TLS 1.3\n• Sensitive data is encrypted at rest in our Supabase-powered database\n• Private messages use end-to-end encryption (E2EE)\n• Passwords are hashed using bcrypt — we never store your plaintext password\n• Payment data is handled by Pesapal under PCI-DSS standards — AfuChat never stores card numbers or mobile money PINs\n• Media files are stored on Cloudflare R2 with access controls\n• We perform regular security reviews and penetration testing\n• Two-factor authentication (2FA) is available and recommended for all accounts\n\nWhile we implement reasonable security measures, no method of internet transmission or electronic storage is 100% secure. In the event of a data breach that affects your rights or freedoms, we will notify you and relevant authorities as required by applicable law.`,
  },

  // ─── 12. Data Retention ────────────────────────────────────
  {
    title: "11. Data Retention",
    body: `We retain your personal information for as long as your account is active or as needed to provide services. Specific retention periods:\n\n• Account data: retained while your account is active; deleted within 30 days of account deletion request\n• Private encrypted messages: purged within 30 days of account deletion (both parties must delete their accounts for full purge)\n• Financial transaction records: retained for 7 years for tax and legal compliance\n• Support communications: retained for 3 years after resolution\n• Log data (IP addresses, access logs): retained for up to 12 months for security purposes\n• AI conversation history: retained until you delete it or delete your account\n• Backup data: encrypted backups are purged within 90 days of account deletion\n\nWhere we are required to retain data for legal, regulatory, or fraud prevention purposes, we will retain only the minimum necessary information.`,
  },

  // ─── 13. Children's Privacy ────────────────────────────────
  {
    title: "12. Children's Privacy",
    body: `AfuChat is not intended for children under the age of 13. We do not knowingly collect personal information from children under 13. If we discover that a child under 13 has provided us with personal information without parental consent, we will promptly delete that account and associated data.\n\nIf you are a parent or guardian and believe your child under 13 has an AfuChat account, please contact us at support@afuchat.com immediately.\n\nUsers aged 13–17 may use the Platform with parental or guardian consent. We take additional care with accounts we identify as belonging to minors, including limiting certain data processing and restricting access to adult content.`,
  },

  // ─── 14. International Transfers ───────────────────────────
  {
    title: "13. International Data Transfers",
    body: `AfuChat is headquartered in Uganda. Your information may be transferred to, stored, and processed in countries other than your country of residence — including the United States, where our primary service providers (Supabase, Cloudflare) operate.\n\nFor transfers from the European Economic Area (EEA) or UK to countries without an adequacy decision, we rely on:\n• Standard Contractual Clauses (SCCs) approved by the European Commission\n• Binding contractual protections with sub-processors\n\nBy using the Platform, you consent to the transfer of your information to these countries, which may have different data protection laws than your country of residence.`,
  },

  // ─── 15. App Stores & Platforms ────────────────────────────
  {
    title: "14. App Store Data Safety Disclosures",
    body: `In compliance with Google Play's Data Safety requirements and Apple's App Privacy Labels, the following summarises our data practices:\n\n━ DATA COLLECTED\n• Personal info: name, email address, user ID\n• Financial info: purchase history (no card numbers stored by AfuChat)\n• Location: approximate location derived from IP address\n• Messages: content of messages you send (private messages are E2EE and not readable by AfuChat)\n• Photos/videos: content you choose to upload\n• App interactions: in-app activity, feature usage\n• App performance: crash logs and diagnostic data\n• Device identifiers: device ID, push token\n\n━ DATA NOT COLLECTED\n• Precise location (GPS)\n• Browsing history outside AfuChat\n• Contacts (unless you choose to sync via the phone contacts feature)\n\n━ DATA SHARING\n• Data may be shared with service providers as described in Section 4\n• Data is not sold\n• Data is not used for advertising to third parties\n\n━ SECURITY PRACTICES\n• Data is encrypted in transit\n• You can request data deletion`,
  },

  // ─── 16. Changes ───────────────────────────────────────────
  {
    title: "15. Changes to This Policy",
    body: `We may update this Privacy Policy from time to time to reflect changes in our practices, technology, legal requirements, or other factors. When we make material changes, we will:\n\n• Post the updated Policy with a new "Last Updated" date\n• Notify you via in-app notification or email (for significant changes)\n• Where required by law, ask for your renewed consent\n\nYour continued use of the Platform after the effective date of any changes constitutes your acceptance of the updated Policy. We encourage you to review this Policy periodically.`,
  },

  // ─── 17. Contact ───────────────────────────────────────────
  {
    title: "16. Contact Us",
    body: `If you have any questions, concerns, or requests regarding this Privacy Policy or our data practices, please contact us:\n\nAfuChat Limited\nKampala, Republic of Uganda\n\nPrivacy enquiries:  privacy@afuchat.com\nGeneral support:    support@afuchat.com\nLegal / compliance: legal@afuchat.com\nWebsite:            https://afuchat.com\n\nFor GDPR-related requests, please include "GDPR Request" in your email subject line. For CCPA requests, include "CCPA Request". We will respond within 30 days of receiving your request.`,
  },
];

export default function PrivacyScreen() {
  const { colors } = useTheme();
  const insets = useSafeAreaInsets();

  return (
    <View style={[styles.root, { backgroundColor: colors.background }]}>
      {/* Header */}
      <View style={[styles.header, { paddingTop: insets.top + 8, borderBottomColor: colors.border }]}>
        <TouchableOpacity
          onPress={() => router.canGoBack() ? router.back() : router.replace("/")}
          style={styles.backBtn}
        >
          <Ionicons name="arrow-back" size={22} color={colors.text} />
        </TouchableOpacity>
        <Text style={[styles.headerTitle, { color: colors.text }]}>Privacy Policy</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView
        contentContainerStyle={[styles.content, { paddingBottom: insets.bottom + 48 }]}
        showsVerticalScrollIndicator={false}
      >
        {/* Intro */}
        <View style={styles.introBlock}>
          <Text style={[styles.pageTitle, { color: colors.text }]}>Privacy Policy</Text>
          <Text style={[styles.updated, { color: colors.textMuted }]}>
            Effective: {EFFECTIVE_DATE} · Last updated: {LAST_UPDATED}
          </Text>

          <View style={[styles.highlightBox, { backgroundColor: colors.surface, borderColor: colors.border }]}>
            <View style={[styles.highlightRow, { borderBottomColor: colors.border }]}>
              <Ionicons name="lock-closed" size={16} color={TEAL} />
              <Text style={[styles.highlightText, { color: colors.text }]}>
                <Text style={{ fontFamily: "Inter_600SemiBold" }}>Private messages are end-to-end encrypted.</Text>
                {" "}We cannot read them — ever.
              </Text>
            </View>
            <View style={[styles.highlightRow, { borderBottomColor: colors.border }]}>
              <Ionicons name="ban" size={16} color="#EF4444" />
              <Text style={[styles.highlightText, { color: colors.text }]}>
                <Text style={{ fontFamily: "Inter_600SemiBold" }}>We do not sell your data</Text>
                {" "}to advertisers or third parties.
              </Text>
            </View>
            <View style={styles.highlightRow}>
              <Ionicons name="trash-outline" size={16} color="#F59E0B" />
              <Text style={[styles.highlightText, { color: colors.text }]}>
                You can{" "}
                <Text style={{ fontFamily: "Inter_600SemiBold" }}>delete your account and data</Text>
                {" "}at any time.
              </Text>
            </View>
          </View>

          <Text style={[styles.intro, { color: colors.textSecondary }]}>
            At AfuChat, your privacy is not an afterthought — it is a core design principle. This Policy explains in plain language what data we collect, why we collect it, and how you stay in control.
          </Text>
        </View>

        {/* Sections */}
        {sections.map((section, i) => (
          <View key={i} style={[styles.section, { borderTopColor: colors.border }]}>
            <Text style={[styles.sectionTitle, { color: colors.text }]}>{section.title}</Text>
            <Text style={[styles.sectionBody, { color: colors.textSecondary }]}>{section.body}</Text>
          </View>
        ))}

        {/* Footer */}
        <View style={[styles.footer, { borderTopColor: colors.border }]}>
          <Ionicons name="shield-checkmark" size={28} color={TEAL} style={{ marginBottom: 10 }} />
          <Text style={[styles.footerTitle, { color: colors.text }]}>Your privacy matters to us.</Text>
          <Text style={[styles.footerSub, { color: colors.textMuted }]}>
            AfuChat Limited · Kampala, Uganda
          </Text>
          <Text style={[styles.footerSub, { color: colors.textMuted }]}>
            privacy@afuchat.com · support@afuchat.com
          </Text>
          <Text style={[styles.footerSub, { color: colors.textMuted }]}>
            © {new Date().getFullYear()} AfuChat Limited. All rights reserved.
          </Text>
          <TouchableOpacity onPress={() => router.push("/terms")} style={{ marginTop: 14 }}>
            <Text style={{ color: TEAL, fontSize: 14, fontFamily: "Inter_500Medium", textAlign: "center" }}>
              View Terms of Service →
            </Text>
          </TouchableOpacity>
          <TouchableOpacity onPress={() => Linking.openURL("mailto:privacy@afuchat.com")} style={{ marginTop: 8 }}>
            <Text style={{ color: "#6B7280", fontSize: 13, fontFamily: "Inter_400Regular", textAlign: "center" }}>
              Data requests: privacy@afuchat.com
            </Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  root:        { flex: 1 },
  header:      { flexDirection: "row", alignItems: "center", paddingHorizontal: 16, paddingBottom: 14, borderBottomWidth: StyleSheet.hairlineWidth },
  backBtn:     { width: 40, height: 40, alignItems: "center", justifyContent: "center" },
  headerTitle: { flex: 1, textAlign: "center", fontSize: 16, fontFamily: "Inter_700Bold" },

  content:    { },

  introBlock:  { paddingHorizontal: 20, paddingTop: 28, paddingBottom: 24, gap: 14 },
  pageTitle:   { fontSize: 26, fontFamily: "Inter_700Bold" },
  updated:     { fontSize: 13, fontFamily: "Inter_400Regular" },

  highlightBox:  { borderWidth: 1, borderRadius: 14, overflow: "hidden" },
  highlightRow:  { flexDirection: "row", alignItems: "flex-start", gap: 10, padding: 14, borderBottomWidth: StyleSheet.hairlineWidth },
  highlightText: { flex: 1, fontSize: 14, fontFamily: "Inter_400Regular", lineHeight: 20 },

  intro:      { fontSize: 15, fontFamily: "Inter_400Regular", lineHeight: 23 },

  section:     { paddingHorizontal: 20, paddingVertical: 24, borderTopWidth: StyleSheet.hairlineWidth },
  sectionTitle:{ fontSize: 17, fontFamily: "Inter_700Bold", lineHeight: 24, marginBottom: 12 },
  sectionBody: { fontSize: 14, fontFamily: "Inter_400Regular", lineHeight: 23 },

  footer:      { borderTopWidth: StyleSheet.hairlineWidth, paddingHorizontal: 20, paddingVertical: 36, alignItems: "center", gap: 5 },
  footerTitle: { fontSize: 16, fontFamily: "Inter_600SemiBold", marginBottom: 4 },
  footerSub:   { fontSize: 12, fontFamily: "Inter_400Regular", textAlign: "center" },
});
