import type { ModuleManifest } from "./types";

export const SUPER_APP_REGISTRY: ModuleManifest[] = [
  {
    id: "afuai",
    name: "AfuAI",
    description: "Your intelligent AI assistant. Ask anything, do everything.",
    version: "1.0.0",
    icon: "sparkles",
    gradient: ["#00BCD4", "#0097A7"] as const,
    keepAlive: true,
    badge: "AI",
  },
  {
    id: "afupay",
    name: "AfuPay",
    description: "Send, receive, top up, and manage your ACoins & Nexa.",
    version: "2.0.0",
    icon: "wallet",
    gradient: ["#34C759", "#00C781"] as const,
    keepAlive: true,
  },
  {
    id: "afumarket",
    name: "AfuMarket",
    description: "Shop from verified stores and sellers.",
    version: "1.0.0",
    icon: "storefront",
    gradient: ["#AF52DE", "#BF5AF2"] as const,
    keepAlive: false,
    badge: "NEW",
  },
  {
    id: "afugames",
    name: "AfuGames",
    description: "Play games and compete with friends.",
    version: "1.0.0",
    icon: "game-controller",
    gradient: ["#FF3B30", "#FF6B35"] as const,
    keepAlive: false,
    badge: "SOON",
    comingSoon: true,
  },
  {
    id: "afumusic",
    name: "AfuMusic",
    description: "Play music from your device library — offline, always.",
    version: "2.0.0",
    icon: "musical-notes",
    gradient: ["#5856D6", "#7B79E8"] as const,
    keepAlive: true,
    nativeOnly: true,
  },
  {
    id: "afubusiness",
    name: "AfuBusiness",
    description: "Tools and analytics for your business.",
    version: "1.0.0",
    icon: "briefcase",
    gradient: ["#1C1C1E", "#3A3A3C"] as const,
    keepAlive: false,
  },
  {
    id: "afusearch",
    name: "AfuSearch",
    description: "Search people, posts, channels, and more.",
    version: "1.0.0",
    icon: "search",
    gradient: ["#5856D6", "#6E6CD3"] as const,
    keepAlive: false,
  },
  {
    id: "afulens",
    name: "AfuLab",
    description: "Point your camera at anything for instant AI answers.",
    version: "2.0.0",
    icon: "scan",
    gradient: ["#FF6B35", "#FF3B00"] as const,
    keepAlive: false,
    badge: "AI",
  },
  {
    id: "afuservices",
    name: "AfuServices",
    description: "Pay bills, top up airtime, and access local services.",
    version: "1.0.0",
    icon: "card",
    gradient: ["#AF52DE", "#BF5AF2"] as const,
    keepAlive: false,
  },
  {
    id: "afufreelance",
    name: "AfuFreelance",
    description: "Hire talent or find work on AfuFreelance.",
    version: "1.0.0",
    icon: "briefcase",
    gradient: ["#34C759", "#30D158"] as const,
    keepAlive: false,
    badge: "NEW",
  },
  {
    id: "afugifts",
    name: "AfuGifts",
    description: "Send animated gifts to people you love.",
    version: "1.0.0",
    icon: "gift",
    gradient: ["#FF3B30", "#FF453A"] as const,
    keepAlive: false,
    badge: "SOON",
    comingSoon: true,
  },
  {
    id: "afuid",
    name: "Digital ID",
    description: "Your verifiable digital identity card.",
    version: "1.0.0",
    icon: "id-card",
    gradient: ["#1E3A5F", "#2C5282"] as const,
    keepAlive: false,
    badge: "3D",
  },
  {
    id: "afuqr",
    name: "QR Scanner",
    description: "Scan any QR code — links, Wi-Fi, contacts and more.",
    version: "1.0.0",
    icon: "qr-code",
    gradient: ["#1C1C1E", "#3A3A3C"] as const,
    keepAlive: false,
    nativeOnly: true,
  },
  {
    id: "afusaved",
    name: "Saved",
    description: "Saved posts, starred messages, and your collections.",
    version: "1.0.0",
    icon: "bookmark",
    gradient: ["#FF6B35", "#FF8C00"] as const,
    keepAlive: false,
  },
  {
    id: "afucollections",
    name: "Collections",
    description: "Curate and share themed collections.",
    version: "1.0.0",
    icon: "albums",
    gradient: ["#BF5AF2", "#AF52DE"] as const,
    keepAlive: false,
  },
  {
    id: "afumatch",
    name: "AfuMatch",
    description: "Meet new people and find meaningful connections.",
    version: "1.0.0",
    icon: "heart",
    gradient: ["#FF2D55", "#FF375F"] as const,
    keepAlive: false,
    badge: "SOON",
    comingSoon: true,
  },
  {
    id: "afuevents",
    name: "Events",
    description: "Discover local and online events near you.",
    version: "1.0.0",
    icon: "calendar",
    gradient: ["#FF9500", "#FFCC00"] as const,
    keepAlive: false,
  },
  {
    id: "afunearby",
    name: "Nearby",
    description: "Scan Bluetooth devices, inspect your Wi-Fi network, and manage home screen shortcuts.",
    version: "1.0.0",
    icon: "radio",
    gradient: ["#007AFF", "#5AC8FA"] as const,
    keepAlive: false,
    nativeOnly: true,
    badge: "NEW",
  },
  {
    id: "afureferral",
    name: "Referral",
    description: "Invite friends and earn Nexa rewards.",
    version: "1.0.0",
    icon: "people",
    gradient: ["#34C759", "#00C781"] as const,
    keepAlive: false,
  },
  {
    id: "afuusernames",
    name: "Usernames",
    description: "Buy and sell premium @handles.",
    version: "1.0.0",
    icon: "at",
    gradient: ["#007AFF", "#5AC8FA"] as const,
    keepAlive: false,
  },
];

export const SUPER_APP_ID_SET = new Set(SUPER_APP_REGISTRY.map((m) => m.id));

export function findModule(id: string): ModuleManifest | undefined {
  return SUPER_APP_REGISTRY.find((m) => m.id === id);
}
