// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/profile-redesign/EditorialLight.tsx": () => import("../components/mockups/profile-redesign/EditorialLight.tsx"),
  "./components/mockups/profile-redesign/ImmersiveDark.tsx": () => import("../components/mockups/profile-redesign/ImmersiveDark.tsx"),
  "./components/mockups/profile-redesign/MinimalGrid.tsx": () => import("../components/mockups/profile-redesign/MinimalGrid.tsx"),
  "./components/mockups/owl-mascot/Layered3D.tsx": () => import("../components/mockups/owl-mascot/Layered3D.tsx"),
  "./components/mockups/owl-mascot/Shaded3D.tsx": () => import("../components/mockups/owl-mascot/Shaded3D.tsx"),
  "./components/mockups/owl-mascot/Smooth2D.tsx": () => import("../components/mockups/owl-mascot/Smooth2D.tsx")
};
